name: Build and Release .NET 10

on:
  release:
    types: [published]

jobs:
  build:
    runs-on: windows-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4 # 升级到推荐的 v4 版本

      - name: Setup .NET 10
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: '10.0.x' # 指定使用 .NET 10 环境

      - name: Publish Single File
        # 这里直接使用你本地验证过的命令，并指定输出目录为 ./publish
        run: |
          dotnet publish SOAPHound.csproj -c Release -r win-x64 -o ./publish
          dir ./publish

      - name: Upload Release assets
        uses: softprops/action-gh-release@v2
        with:
          files: |
            publish/SOAPHound.exe
        env:
          GITHUB_TOKEN: ${{ secrets.PAT_TOKEN }}